Repository strapi/sdk-plugin, pull requests merged in 2025-02, with the labels that each got.

#82 ci: remove corepack
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: pr: chore, source: sdk-plugin

#81 fix: allow any file extension in exports string
  .changeset/smart-eyes-cross.md
  src/cli/commands/utils/pkg.ts
Labels: pr: fix, source: sdk-plugin

#72 fix: update the route syntax for it to be properly registered
  .changeset/angry-kings-shout.md
  src/cli/commands/plugin/init/files/server.ts
Labels: pr: fix, source: sdk-plugin, community
